/*
 * AutomataSVGDocument.java
 *
 * Created on 5. helmikuuta 2004, 21:53
 */

package org.rikastamo.automata;

/**
 *
 * @author  rannala
 */
public class AutomataSVGDocument extends javax.swing.JInternalFrame {
    
    /** Creates new form AutomataSVGDocument */
    public AutomataSVGDocument() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
