/*
 * automataApp.java
 *
 * Created on 5. joulukuuta 2003, 22:00
 */

package org.rikastamo.automata;

/**
 *
 * @author  rannala
 */
//import javax.swing.JFileChooser;
//import javax.swing.filechooser.FileFilter;
//import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.tree.*;

import org.jdom.DocType;
import org.jdom.Document;
import org.jdom.Element;
import org.jdom.JDOMException;
import org.jdom.Namespace;
//import org.jdom.input.DOMBuilder;
//import org.jdom.input.SAXBuilder;
import org.jdom.output.XMLOutputter;
//import org.jdom.input.DefaultJDOMFactory;
//import org.jdom.DefaultJDOMFactory;
import org.jdom.Attribute;
//import org.jdom.input.Builder;
import org.jdom.input.SAXBuilder;
import java.io.File;
//import java.io.IOException;
import java.io.*;
import java.util.List;
import java.util.Enumeration;

import java.util.Vector;

public class AutomataApp extends javax.swing.JFrame {
    AutomataEngine engine = null;
    static Document document;
    Vector documents = new Vector();
    static String VERSION = "0.9";
    AutomataProperties ap;
    DefaultTreeModel treeModel;
    DefaultMutableTreeNode root;
    
    /** Creates new form automataApp */
    public AutomataApp() {
        initComponents();
        this.setTitle("Automata " + VERSION);        
        engine = new AutomataEngine();
        this.setIconImage(new ImageIcon("automata.gif").getImage());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        rectangleButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        textButton = new javax.swing.JButton();
        guideButton = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        root = new DefaultMutableTreeNode("Elements");
        treeModel = new DefaultTreeModel(root);
        jTree2 = new javax.swing.JTree(root);
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTable3 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        NewDocument = new javax.swing.JMenuItem();
        NewImage = new javax.swing.JMenuItem();
        NewMuu = new javax.swing.JMenuItem();
        SaveAs = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        View = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        Tools = new javax.swing.JMenu();
        Options = new javax.swing.JMenuItem();

        jMenu2.setText("Menu");
        jMenuBar2.add(jMenu2);

        setFont(new java.awt.Font("Dialog", 0, 10));
        setName("AutomataFrame"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel6.setMinimumSize(new java.awt.Dimension(120, 30));
        jPanel6.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        rectangleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/draw.gif"))); // NOI18N
        rectangleButton.setToolTipText("Draw objects");
        rectangleButton.setFocusCycleRoot(true);
        rectangleButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        rectangleButton.setMaximumSize(new java.awt.Dimension(60, 60));
        rectangleButton.setMinimumSize(new java.awt.Dimension(30, 30));
        rectangleButton.setPreferredSize(new java.awt.Dimension(40, 40));
        rectangleButton.setSelected(true);
        rectangleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDrawing(evt);
            }
        });
        jPanel6.add(rectangleButton);

        selectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/select.gif"))); // NOI18N
        selectButton.setToolTipText("Select objects");
        selectButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        selectButton.setMaximumSize(new java.awt.Dimension(60, 60));
        selectButton.setMinimumSize(new java.awt.Dimension(30, 30));
        selectButton.setPreferredSize(new java.awt.Dimension(30, 30));
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTool(evt);
            }
        });
        jPanel6.add(selectButton);

        textButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fill.gif"))); // NOI18N
        textButton.setToolTipText("Fill objects");
        textButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        textButton.setMaximumSize(new java.awt.Dimension(60, 60));
        textButton.setMinimumSize(new java.awt.Dimension(30, 30));
        textButton.setPreferredSize(new java.awt.Dimension(30, 30));
        textButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillTool(evt);
            }
        });
        jPanel6.add(textButton);

        guideButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guide.gif"))); // NOI18N
        guideButton.setToolTipText("Toggle guides");
        guideButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        guideButton.setMaximumSize(new java.awt.Dimension(60, 60));
        guideButton.setMinimumSize(new java.awt.Dimension(30, 30));
        guideButton.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel6.add(guideButton);

        jPanel7.add(jPanel6, java.awt.BorderLayout.NORTH);

        jToolBar2.add(jPanel7);

        jPanel1.add(jToolBar2, java.awt.BorderLayout.NORTH);

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setDoubleBuffered(true);
        jToolBar1.setMinimumSize(new java.awt.Dimension(300, 200));
        jToolBar1.setPreferredSize(new java.awt.Dimension(240, 600));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("View document info");
        jTabbedPane1.setName("nam"); // NOI18N

        jPanel2.setToolTipText("view layer info");
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"name", ""},
                {"type", ""},
                {"bgcolor", ""},
                {"text size", ""},
                {"text color", ""},
                {"height", ""},
                {"width", ""}
            },
            new String [] {
                "name", "value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jPanel2.add(jTable1);

        jTabbedPane1.addTab("Element", jPanel2);

        jPanel5.setToolTipText("view layers");
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setToolTipText("select");

        jTree2.setEditable(true);
        jScrollPane1.setViewportView(jTree2);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(41, 33));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton4.setText("up");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveElementUp(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setText("down");
        jPanel3.add(jButton5);

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteElement(evt);
            }
        });
        jPanel3.add(jButton6);

        jPanel5.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Layers", jPanel5);

        jPanel4.setToolTipText("View whitespace used");
        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"covered area", "0"},
                {"color 1 area", "0"},
                {"color 2 area", "0"},
                {"color 3 area", "0"},
                {"snap to grid", null}
            },
            new String [] {
                "item", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setToolTipText("Viewe document properties");
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jTable2.setSurrendersFocusOnKeystroke(true);
        jPanel4.add(jTable2);

        jLabel1.setText("This feature allows you to calculate the area used for different areas of  the design.");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setMinimumSize(new java.awt.Dimension(140, 15));
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 15));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel4.add(jLabel1);

        jTabbedPane1.addTab("Document", jPanel4);

        jPanel8.setToolTipText("Control colors");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPanel8.add(jTable3);

        jTabbedPane1.addTab("Colors", jPanel8);

        jToolBar1.add(jTabbedPane1);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.EAST);
        jToolBar1.getAccessibleContext().setAccessibleParent(jPanel1);

        jDesktopPane1.setBackground(new java.awt.Color(0, 204, 255));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(40, 30));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setToolTipText("Choose from menu");

        File.setText("File");
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        File.add(Open);

        jMenu1.setText("New..");

        NewDocument.setText("New webpage..");
        NewDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewDocumentActionPerformed(evt);
            }
        });
        jMenu1.add(NewDocument);

        NewImage.setText("New Image");
        NewImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewImageActionPerformed(evt);
            }
        });
        jMenu1.add(NewImage);

        NewMuu.setText("New vector..");
        NewMuu.setEnabled(false);
        NewMuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewMuuActionPerformed(evt);
            }
        });
        jMenu1.add(NewMuu);

        File.add(jMenu1);

        SaveAs.setText("Save As...");
        SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsActionPerformed(evt);
            }
        });
        File.add(SaveAs);

        jMenuBar1.add(File);

        Edit.setText("Edit");
        Edit.setEnabled(false);

        jMenuItem1.setText("Undo");
        Edit.add(jMenuItem1);

        jMenuItem2.setText("Redo");
        Edit.add(jMenuItem2);
        Edit.add(jSeparator1);

        jMenuItem3.setText("Cut");
        Edit.add(jMenuItem3);

        jMenuItem4.setText("Copy");
        Edit.add(jMenuItem4);

        jMenuItem5.setText("Item");
        Edit.add(jMenuItem5);

        jMenuBar1.add(Edit);

        View.setText("View");
        View.setEnabled(false);

        jMenuItem6.setText("Properties");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowProperties(evt);
            }
        });
        View.add(jMenuItem6);

        jMenuBar1.add(View);

        Tools.setText("Tools");
        Tools.setEnabled(false);

        Options.setText("Options");
        Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsActionPerformed(evt);
            }
        });
        Tools.add(Options);

        jMenuBar1.add(Tools);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteElement(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteElement
       // TODO add your handling code here: poista puusta ja elementtitaulusta
    }//GEN-LAST:event_DeleteElement

    private void MoveElementUp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveElementUp
        // TODO add your handling code here: muuta järjestystä puussa ja elementtitaulussa
        
    }//GEN-LAST:event_MoveElementUp
    private void fillTool(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillTool
        // TODO add your handling code here: 
    }//GEN-LAST:event_fillTool

    private void selectTool(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTool
        if(!documents.isEmpty() && documents.indexOf(jDesktopPane1.getSelectedFrame()) != -1){
            AutomataDocument ad = (AutomataDocument)(documents.elementAt(documents.indexOf(jDesktopPane1.getSelectedFrame())));
            if(ad!= null) ad.canvas2.setTool(1);
        }
    }//GEN-LAST:event_selectTool

    private void startDrawing(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDrawing
         if(!documents.isEmpty() && documents.indexOf(jDesktopPane1.getSelectedFrame()) != -1){
        AutomataDocument ad = (AutomataDocument)(documents.elementAt(documents.indexOf(jDesktopPane1.getSelectedFrame())));
        if(ad!= null) ad.canvas2.setTool(0);
         }
    }//GEN-LAST:event_startDrawing

    private void ShowProperties(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowProperties
        if(ap != null)
        if(!ap.isVisible()){
        ap.setVisible(true);
        }else{
        ap.setVisible(false);
        }
    }//GEN-LAST:event_ShowProperties

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Add your handling code here:
        //ask for saving work!!
        // new java.awt.event.ActionEvent();
    }//GEN-LAST:event_formWindowClosed

    private void OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsActionPerformed
        // Add your handling code here:
        AutomataOptions opt = new AutomataOptions(this, false);
        opt.setSize(400, 300);
        opt.setVisible(true);
        //pitäs varmaan jotenkin välittää myös optionit dokumenttiin :)
    }//GEN-LAST:event_OptionsActionPerformed
    
    private void SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsActionPerformed
        // Add your handling code here: saving the document corresponding to currently open document!!
          int valittu = documents.indexOf(jDesktopPane1.getSelectedFrame()); 
          SaveDocument(valittu);
    }
    private void SaveCSSDocument(int valittu, File filename){
        String work = " ";
        AutomataDocument ad = (AutomataDocument)(documents.elementAt(valittu));
        ad.setSaved();
        Vector adv = ad.getVector();
        int laskuri = adv.size()-1;
            for(int x = 0; x <= laskuri; x++){
                 AutomataElement ae = (AutomataElement)(ad.getVector().elementAt(x));
                        java.awt.Rectangle rec = (java.awt.Rectangle)(ae.rec);
                        ae = null;
                //java.awt.Rectangle rec = (java.awt.Rectangle)(ad.getVector().elementAt(x));
                String width = "width: " + (int)(rec.getWidth()) + "px; \n" ;
                String height = "height: " + (int)(rec.getHeight()) + "px;\n";
                String xt = "left: " + (int)(rec.getX()) + "px;\n";
                String yt = "top: " + (int)(rec.getY()) + "px;\n";
                String text = "font-size: " + (int)(rec.getHeight()*0.8)  +  "px;";
                      
                String att = "position: absolute; \n" + width + height + xt + yt + "\n";
                //String att = "position: absolute; \n" + width + height + xt + yt + "padding: 3px;\ncolor: red;\n border: 3px;\n";          
                work = work + "#a" + x + "{\n" + att + "}\n";
            }
                    //save string as text file
                     try {
                        File myFile =  filename; //new File(filename);       
                        FileOutputStream outStream = new FileOutputStream(myFile);
                        PrintWriter out = new PrintWriter(outStream); 
                        out.println(work);
                        out.close();
                        //return "File " + filename + " successfully written.";
                    } catch(Exception e) {
                        System.out.println("Error writing to file " + filename + "\n"+e);
                        //return "Error writing file " + filename ;
                    }
                    
                    /*pitäskö generoida myös html tiedosto, jossa yhtä monta diviä numeroiduilla nimillä ja käyttää 
                    annettua tiedostoa stylenä*/
    }
    private void SaveSVGDocument(int valittu, File filename){
             try{                
                        File f = filename; //new File(filename);    
                        SAXBuilder builder= new SAXBuilder();         
                        if(f.exists()){
                            document =  builder.build(filename);
                        }else{
                        document = new Document();
                        }
                        Namespace ns = Namespace.getNamespace("svg", "http://www.w3.org/1999/xhtml");
                        DocType svg_doc = new DocType("svg", "-//W3C//DTD SVG 20000303 Stylable//EN", "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd");
                        document.setDocType(svg_doc);
                        Element svg = new Element("svg");
                        document.setRootElement(svg);
                        
                        AutomataDocument ad = (AutomataDocument)(documents.elementAt(valittu));
                        ad.setSaved();
                        Vector adv = ad.getVector();
                        int laskuri = adv.size()-1;
                        
                       AutomataElement aes = (AutomataElement)(ad.getVector().elementAt(0));
                       java.awt.Rectangle tausta = (java.awt.Rectangle)(aes.rec);
                       aes = null;
                       //java.awt.Rectangle tausta = (java.awt.Rectangle)(ad.getVector().elementAt(0));
                        
                        svg.setAttribute("width", Double.toString(tausta.getWidth()));
                        svg.setAttribute("height", Double.toString(tausta.getHeight()));
                       
                        
                        for(int x = 1; x <= laskuri; x++){ 
                            AutomataElement ae = (AutomataElement)(ad.getVector().elementAt(x));
                            java.awt.Rectangle rec = (java.awt.Rectangle)(ae.rec);
                            ae = null;
                            //java.awt.Rectangle rec = (java.awt.Rectangle)(ad.getVector().elementAt(x));
                            Element rect = new Element("rect");
                            rect.setAttribute("x", Double.toString(rec.getX()));
                            rect.setAttribute("y",Double.toString(rec.getY()));
                            rect.setAttribute("width", Double.toString(rec.getWidth()));
                            rect.setAttribute("height",Double.toString(rec.getHeight()));
                            rect.setAttribute("fill", "green"); //get color from doc!!
                            svg.addContent(rect);
                        }                
                        f.createNewFile(); 
                    OutputStream out = (OutputStream)new FileOutputStream(f);  
                    XMLOutputter fmt = new XMLOutputter();
                   fmt.output(document, out);
        }catch(Exception ioe) {
                    ioe.printStackTrace();
                }
                        
    }
    private void SaveHTMLDocument(int valittu, File filename){
        try{
                        File f = filename; //new File(filename);    
                        SAXBuilder builder= new SAXBuilder();         
                        if(f.exists()){
                            document =  builder.build(filename);
                        }else{
                        document = new Document();
                        }
                        Namespace ns = Namespace.getNamespace("xhtml", "http://www.w3.org/1999/xhtml");

                        DocType xhtml = new DocType("html", "-//W3C//DTD XHTML 1.0 Transitional//EN", "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd");
                        document.setDocType(xhtml);
                    
                        Element html = new Element("html");
                        document.setRootElement(html);
                        Element head = new Element("head");
                        Element title = new Element("title");
                        title.addContent("generated with Automata " + VERSION);
                        Element body = new Element("body");
                        head.addContent(title);
                        html.addContent(head);              
                    AutomataDocument ad = (AutomataDocument)(documents.elementAt(valittu));
                    ad.setSaved();
                    Vector adv = ad.getVector();
                    int laskuri = adv.size()-1;
                    for(int x = 0; x <= laskuri; x++){                 
                        Element div = new Element("div");   
                        AutomataElement ae = (AutomataElement)(ad.getVector().elementAt(x));
                        java.awt.Rectangle rec = (java.awt.Rectangle)(ae.rec);
                        ae = null;
                        String width = "width: " + (int)(rec.getWidth()) + "px; ";
                        String height = "height: " + (int)(rec.getHeight()) + "px; ";
                        String xt = "left: " + (int)(rec.getX()) + "px; ";
                        String yt = "top: " + (int)(rec.getY()) + "px; ";
                        String text = "font-size: " + (int)(rec.getHeight()*0.8)  +  "px;";
                        //borderien kehittely, hae tän rectangles sisällä olevasta rectanglesta vai luodaanko uusi vektori niitä varten???
                        String att = "position: absolute; " + width + height + xt + yt + text + "padding: 3px; color: red; border: 3px;"; 
                        String color = "";
                        if(x>=1){ 
                            color = "background-color: #EBE7DB;";
                            div.addContent(new Integer(x).toString());
                        }
                        div.setAttribute(new Attribute("style", att+color));   
                        body.addContent(div);
                    }
                    //laita muiden random vektoriobjektien tilalle rectangle?
                    html.addContent(body);
                    f.createNewFile(); 
                    OutputStream out = (OutputStream)new FileOutputStream(f);  
                    XMLOutputter fmt = new XMLOutputter();
                   fmt.output(document, out);
        }catch(Exception ioe) {
                    ioe.printStackTrace();
                }
    }
    private void SaveDocument(int valittu){
        if(!documents.isEmpty()){
        JFileChooser chooser = new JFileChooser(System.getProperty("user.dir"));
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        ExampleFileFilter filter = new ExampleFileFilter();
        filter.addExtension("html");
        filter.addExtension(".svg");
        filter.addExtension(".css");
        filter.setDescription("HTML files");
        chooser.setFileFilter(filter);
        chooser.setVisible(true);
        int returnVal = chooser.showSaveDialog(this);
        switch (returnVal) {
            case JFileChooser.APPROVE_OPTION:
                String filename = chooser.getSelectedFile().getName();
                String dirikka = chooser.getCurrentDirectory().toString();                          
                    if( chooser.getSelectedFile().exists()){
                        int response = JOptionPane.showConfirmDialog(null, "Overwrite existing file?", "Confirm Overwrite",JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if( response == JOptionPane.CANCEL_OPTION){ 
                             break;
                        }
                    }
                    if(valittu == -1){
                            System.out.println("nothing to save");
                            break;
                    } 
                //SaveHTMLDocument(valittu, chooser.getSelectedFile().toURI().toString());
                     //SaveHTMLDocument(valittu, chooser.getSelectedFile());
                 if(filename.endsWith(".html")){
                     SaveHTMLDocument(valittu, chooser.getSelectedFile());
                 }else if(filename.endsWith(".css")){
                    SaveCSSDocument(valittu, chooser.getSelectedFile());
                 }else if(filename.endsWith(".svg")){
                    SaveSVGDocument(valittu, chooser.getSelectedFile());
                 }
                break;
            case JFileChooser.CANCEL_OPTION:
                // Cancel or the close-dialog icon was clicked
                System.out.println("file save cancelled");
                break;
            case JFileChooser.ERROR_OPTION:
                // The selection process did not complete successfully
                System.out.println("file save error");
                break;
        }  
        }
    }//GEN-LAST:event_SaveAsActionPerformed
    private void OpenDocument(){
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        ExampleFileFilter filter = new ExampleFileFilter();
        filter.addExtension("html");
        filter.addExtension("jpg");
        filter.addExtension("svg");
        filter.addExtension("css");
      
        //filter.addExtension("jpg");
        filter.setDescription("HTML, SVG and JPG files");
        //filter.setDescription("HTML, JPG and SVG files");
        chooser.setFileFilter(filter);
        chooser.setVisible(true);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
              File file = chooser.getSelectedFile(); 
              //DefaultJDOMFactory factory;
            if(chooser.getSelectedFile().getName().endsWith(".html")){
                System.out.println("Attempting to create the document from a html file");
                OpenHTMLDocument(file);
            }else if(chooser.getSelectedFile().getName().endsWith(".css")){
                System.out.println("Attempting to create the document from a css file");
                OpenCSSDocument(file);
            }else if(chooser.getSelectedFile().getName().endsWith(".svg")){
                System.out.println("Attempting to create the document from a svg file");
                OpenSVGDocument(file);
            }else if(chooser.getSelectedFile().getName().endsWith(".jpg")){
                System.out.println("Attempting to create the document from a jpg file");
                OpenJPGDocument(file);
            }else{
                System.out.println("error identifying file type");
            }
            }
    }
    private void OpenHTMLDocument(File file){
        AutomataDocument docu = new AutomataDocument(this);
                try {
                    Namespace ns = Namespace.getNamespace("xhtml", "http://www.w3.org/1999/xhtml");
                    SAXBuilder builder = new SAXBuilder(true);
                    Document doc = builder.build(file); 
                    if(doc != null && doc.hasRootElement()){
                        Element root = doc.getRootElement();               
                        Element body = root.getChild("body", ns);
                        List divs = body.getChildren("div", ns);
                        //go through the list and add rectangles    
                        int suurin_x = 0;
                        int suurin_y = 0;
                    for (int i=0; i<divs.size(); ++i) {
                        int width = 100;
                        int height = 200;
                        int x = 20;
                        int y = 40;
                        Element curTeam = (Element) divs.get(i);
                        String style = curTeam.getAttribute("style").getValue();
                      //  System.out.println("tyyli: " + style);
                        //get access to width, height, top and left
                        //käy läpi kaikki 1) etsien seuraava = 2) hae ensimmäinen sana 3) etsi ; paikka 4) muuta jäljellä oleva pätkä intiksi yms.           
                        
                        while(style.endsWith(";")){
                            String nimi = style.substring(0, style.indexOf(":")).trim();
                            String value = style.substring(style.indexOf(":")+1, style.indexOf(";")).trim();
                            //System.out.println(nimi + "=" + value);
                            style = style.substring(style.indexOf(";")+1);
                            if(nimi.equalsIgnoreCase("width")) width = Integer.parseInt(value.substring(0, value.indexOf("px")));
                            if(nimi.equalsIgnoreCase("height")) height = Integer.parseInt(value.substring(0, value.indexOf("px")));
                            if(nimi.equalsIgnoreCase("top")) y = Integer.parseInt(value.substring(0, value.indexOf("px")));
                            if(nimi.equalsIgnoreCase("left")) x = Integer.parseInt(value.substring(0, value.indexOf("px")));                          
                            if(width>=suurin_x) suurin_x = width;
                            if(height>=suurin_y) suurin_y = height;
                        }
                        java.awt.Rectangle rec = new java.awt.Rectangle(x, y ,width, height);
                  //      docu.canvas2.rectangles.add(rec);
                        docu.canvas2.elements.add(new AutomataElement(rec));
              }
                    //   docu.canvas2.rectangles.add(new java.awt.Rectangle(0, 0 ,suurin_x, suurin_y));
                        docu.canvas2.elements.add(new AutomataElement(new java.awt.Rectangle(0, 0 ,suurin_x, suurin_y)));
                        docu.setSize(suurin_x, suurin_y);
                        docu.setDimensions(suurin_x, suurin_y);
                    }
                    }
            // indicates a well-formedness error
                catch (JDOMException e) { 
                    System.out.println("document is not well-formed.");
                    System.out.println(e.getMessage());
                } catch (NullPointerException e){
                    System.out.println(e.getMessage());    
                    e.printStackTrace();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                     e.printStackTrace();
                }
                documents.add(docu);
                jDesktopPane1.add(docu);
                docu.setVisible(true);
    }
    private void OpenCSSDocument(File file){
        AutomataDocument docu = new AutomataDocument(this); 
        try{
            FileInputStream inStream = new FileInputStream(file);
            BufferedInputStream bis = new BufferedInputStream(inStream); 
            DataInputStream inData = new DataInputStream (bis);
            
            String css = ""; //inData.readUTF();
            String yada;
            while ( (yada=inData.readLine()) != null ) {  
                css = css+yada;         
            }
            
            //System.out.println(css);
            inData.close ();
            int suurin_x = 800;
            int suurin_y = 800;
            int height = 100, width = 100, y = 100, x = 100;
            while(css.length() >= 1){
                //find #
                String name = css.substring(css.indexOf("#"), css.indexOf("{"));
                System.out.println("name: " + name);
                //find { and }
                String rect = css.substring(css.indexOf("{")+1,css.indexOf("}")); 
                //System.out.println("div: " + rect);
                //find ;
                while(rect.length() >= 1){           
                    String item = rect.substring(0, rect.indexOf(";"));
                    String item_name = item.substring(0, item.indexOf(":")).trim();
                    String item_value = item.substring(item.indexOf(":")+1).trim();
                    rect = rect.substring(rect.indexOf(";")+1); 
                   
                    System.out.println("item: " + item); 
                    System.out.println("item_name:" + item_name + "?");
                    System.out.println("item_value:" + item_value + "?");
               
                   if(item_name.equals("height")){
                        height = Integer.parseInt(item_value.substring(0, item_value.indexOf("px")));
                        System.out.println("height: " + height);
                   }else if(item_name.equals("width")){
                             width = Integer.parseInt(item_value.substring(0, item_value.indexOf("px")));
                             System.out.println("width: " + width);
                    }else if(item_name.equals("left")){
                             x = Integer.parseInt(item_value.substring(0, item_value.indexOf("px")));
                              System.out.println("x: " + x);
                    }else if(item_name.equals("top")){    
                             y = Integer.parseInt(item_value.substring(0, item_value.indexOf("px")));
                              System.out.println("y: " + y);
                    }
                    
                    if(width>=suurin_x) suurin_x = width;
                    if(height>=suurin_y) suurin_y = height;
                }
                    //find }
                //System.out.println("ennen" + css);
                css = css.substring(css.indexOf("}")+1);
                //System.out.println("jälkeen"+css);
                java.awt.Rectangle rec = new java.awt.Rectangle(x, y ,width, height);
                //docu.canvas2.rectangles.add(rec);  
                docu.canvas2.elements.add(new AutomataElement(rec));
            }       
            docu.setDimensions(suurin_x, suurin_y);
            docu.setSize(suurin_x, suurin_y);
          //  docu.canvas2.rectangles.add(new java.awt.Rectangle(0, 0 ,suurin_x, suurin_y));
            docu.canvas2.elements.add(new AutomataElement(new java.awt.Rectangle(0, 0 ,suurin_x, suurin_y)));
            //
        }catch(Exception e){
           System.out.println(e.getMessage()); 
        }
         documents.add(docu);
         jDesktopPane1.add(docu);
         docu.setVisible(true);
    }
    private void OpenSVGDocument(File file){
        AutomataDocument docu = new AutomataDocument(this); 
        Namespace ns = Namespace.getNamespace("svg", "http://www.w3.org/1999/xhtml");
        SAXBuilder builder = new SAXBuilder(true);
        try{
            Document doc = builder.build(file); 
            if(doc != null && doc.hasRootElement()){
               Element root = doc.getRootElement();
               String s = root.getAttribute("width").getValue();
               int width1 = Integer.parseInt(s.substring(0, s.indexOf(".0")));
               String s2 = root.getAttribute("height").getValue();
               int height2 = Integer.parseInt(s2.substring(0, s2.indexOf(".0")));
               docu.setSize(width1, height2);
               docu.setDimensions(width1, height2);
               
               List rects = root.getChildren("rect", ns);
               for (int i=0; i<rects.size(); ++i) {
                   Element curTeam = (Element) rects.get(i); 
                    
                   //taitaa tääkin vielä kusta
                    int y = (int)Double.parseDouble(curTeam.getAttribute("y").getValue());
                    int x = (int)Double.parseDouble(curTeam.getAttribute("x").getValue());
                    int width = (int)Double.parseDouble(curTeam.getAttribute("width").getValue());
                    int height = (int)Double.parseDouble(curTeam.getAttribute("height").getValue());
                          
                    java.awt.Rectangle rec = new java.awt.Rectangle(x, y ,width, height);
                //    docu.canvas2.rectangles.add(rec); 
                    docu.canvas2.elements.add(new AutomataElement(rec));
               }
            }
            documents.add(docu);
            jDesktopPane1.add(docu);
            docu.setVisible(true);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    private void OpenJPGDocument(File file){
              //lue kuva
                  //TODO pitäskö olla oma JPGDocument luokka?
             try{
                java.awt.Image image = javax.imageio.ImageIO.read(file);
                // FileInputStream inStream = new FileInputStream(file);
            //lue kuvan koko
                int width1 = image.getWidth(this);
                int height2 = image.getHeight(this);
                System.out.println("kuvan leveys " + width1 + " ja korkeus " + height2);
              AutomataDocument docu = new AutomataDocument(this, image, height2, width1);
             //docu.setSize(width1, height2);
               
               docu.setDimensions(width1, height2);
           
             //java.awt.Rectangle rec = new java.awt.Rectangle(x, y ,width, height);
            //luo kuvan kokoinen kanvas vai rajaa kanvas vasta kuvaelementin tunnistuksen jälkeen
               //  docu.canvas2.elements.add(new AutomataElement(rec));
                //lisää kuvatiedosto dokumenttiin kuva kanvaksessa?
                //docu.canvas2.elements.add(new AutomataElement(rec));
                 documents.add(docu);
                jDesktopPane1.add(docu);
                docu.setVisible(true);
             }catch(Exception e){
            System.out.println(e.getMessage());
        }
             
    }
    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        OpenDocument();
    }//GEN-LAST:event_OpenActionPerformed
    
    private void NewDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewDocumentActionPerformed
        CreateGrid cg = new CreateGrid(this, true);
        cg.setBounds(200, 200, 500, 400);
        cg.setVisible(true);
    }//GEN-LAST:event_NewDocumentActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
         if(!documents.isEmpty()){ // && !((AutomataDocument)(documents.elementAt(documents.indexOf(jDesktopPane1.getSelectedFrame())))).getSaved()){
         int response = JOptionPane.showConfirmDialog(null, "Exiting application without saving?", "Closing program",JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
         if( response == JOptionPane.OK_OPTION){ 
               //dispose();
               System.exit(0);
         } else if( response == JOptionPane.CANCEL_OPTION){    
             //do nothing
             //dispose();
         }  
         }
    }//GEN-LAST:event_exitForm

    private void NewMuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewMuuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewMuuActionPerformed

    private void NewImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewImageActionPerformed
        // TODO ei avata dokumentin teko ikkunaa vaan kuvan valinta
        
        //luodaan suoraan dokumentti
          // AutomataDocument ad = new AutomataDocument(this, true);
}//GEN-LAST:event_NewImageActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new AutomataApp().show();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem NewDocument;
    private javax.swing.JMenuItem NewImage;
    private javax.swing.JMenuItem NewMuu;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Options;
    private javax.swing.JMenuItem SaveAs;
    private javax.swing.JMenu Tools;
    private javax.swing.JMenu View;
    private javax.swing.JButton guideButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    public javax.swing.JTree jTree2;
    private javax.swing.JButton rectangleButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JButton textButton;
    // End of variables declaration//GEN-END:variables
    public void addWindow(AutomataDocument docu, int height, int width){
        jDesktopPane1.add(docu);
        documents.add(docu);
        docu.setSize(height, width);
        docu.setVisible(true); 
        //openPropertiesWindow(docu);
    }
    
  public void openPropertiesWindow(AutomataDocument docu){
        if(ap==null){
            ap = new AutomataProperties(docu);
            jDesktopPane1.add(ap);
            ap.setSize(250, jDesktopPane1.getHeight());
            ap.setVisible(true); 
        }else{
            ap.setDocument(docu);
        }
  }
    /**
     *saves and closes the chosen document, # given as an argument
     **/
    public void saveAndClose(int a){
        //save the given file
        SaveDocument(a);
        //remove document from vector
        documents.remove(a);
        ///TODO: toinen auki oleva dokumentti aktiiviseksi ja tiedot dokumentti tabiin
        ///TODO: document-tabi tyhjäksi jos ei muita dokumentteja auki
    }
   
    public void updateLayersTree(){
        
    //get selected document
          //TODO ilmeisesti tää documents homma saa melkein aina -1:n koska ikkuna ei ole valittuna by default!
        //miten haetaan ylin auki oleva?
        if(!documents.isEmpty() && documents.indexOf(jDesktopPane1.getSelectedFrame()) != -1){
            AutomataDocument ad = (AutomataDocument)(documents.elementAt(documents.indexOf(jDesktopPane1.getSelectedFrame())));
             
       if(ad != null){
       Vector data = ad.canvas2.elements;
       jTree2.removeAll();
       //fill tree with elements vector
      
       if(!data.isEmpty()){
            for(Enumeration enume = data.elements(); enume.hasMoreElements();){
                System.out.println("row added");
                AutomataElement e =  (AutomataElement)data.elements().nextElement();
                DefaultMutableTreeNode child1 = new DefaultMutableTreeNode("element " + e.name);
                //DefaultMutableTreeNode root = (DefaultMutableTreeNode)treeModel.getRoot();
                root.add(child1);
                //(childNode, parent, parent.getChildCount())
                treeModel.insertNodeInto(child1, root, treeModel.getChildCount(root)); //(childNode, parent, parent.getChildCount());
            }
       }else{
             System.out.println("data empty");
               
       }
       }else{
             System.out.println("ad null");
       }
       }
       //TODO puussa olevien tasotietojen päivitys?
       jTree2.setModel(treeModel);
       //jTree2.repaint();
}
    
    class ExampleFileFilter extends javax.swing.filechooser.FileFilter {
        private String[] extensions = new String[10];
        private int count = 2;
        private String kuvaus = "File filter";
        public boolean accept(File file) {
            if (file.isDirectory()) {
                return true;
            }
            String filename = file.getName();
            return (filename.endsWith(".jpg") || filename.endsWith(".html") || filename.endsWith(".svg") || filename.endsWith(".css"));
        }
        public String getDescription() {
            return "*.html, *.css, *.jpg and *.svg";
        }
        public void addExtension(String nimi){
            extensions[count] = nimi;
            count++;
        }
        public void setDescription(String kuvaus2){
            kuvaus = kuvaus;
        }
    }
    
}
