/*
 * createGrid.java
 *
 * Created on 5. joulukuuta 2003, 22:17
 */

package org.rikastamo.automata;

/**
 *
 * @author  rannala
 */
import java.awt.Component;
public class CreateGrid extends javax.swing.JDialog {
    AutomataApp parent;
    int width = 500;
    int height = 500;
    int border = 6;
    String[] fibo = {"2", "3", "5", "8", "13", "21", "34", "55", "89"}; //throw away 0, 1, 1
    int[] fiboint = {2, 3, 5, 8, 13, 21, 34, 55, 89};
    String[] kerroin = {"1:6", "1:5", "1:4", "1:3", "1:2", "1:1", "2:1", "3:1", "4:1", "5:1", "6:1"};
    
    double[] kerroindouble = {0.09016, 0.1458942, 0.236063, 0.3819610809, 0.61803, 1, 1.6180339, 2.61803370154921, 4.2360672, 6.854100462, 11.090166902};
   //PAL 768x576
    String[] preset = {"Webpage 800", "Webpage 1024", "A4", "TV 3:4", "TV 16:9", "Custom", " ", " ", " "};
    int[] preset_x = {800, 1024, 800, 768, 1600, 100, 200, 300, 400};
    int[] preset_y = {800, 1024, 600, 576, 900, 100, 200, 300, 400};
    /** Creates new form createGrid */
    
    public CreateGrid(java.awt.Frame parent2, boolean modal) {
        super(parent2, modal);
        parent = (AutomataApp) parent2;
        initComponents();
       // jTabbedPane1.setTitleAt(0, "File Attributes");
      //  jTabbedPane1.setTitleAt(0, "Dimensions");
      //  jTabbedPane1.setTitleAt(1, "Background Grid");
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        for(int a = 0; a<=8; a++){
            jComboBox1.addItem(fibo[a]);
            jComboBox2.addItem(fibo[a]);
            Presets.addItem(preset[a]);
        }
        jComboBox1.setSelectedIndex(5);
        jComboBox2.setSelectedIndex(5);
        for(int b = 0; b<=10; b++){
            jComboBox3.addItem(kerroin[b]);         
        }
        jComboBox3.setSelectedIndex(5);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        Presets = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setTitle("Create new grid");
        setName("Create new grid");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jTabbedPane1.setToolTipText("doc");
        jTabbedPane1.setName("Document");
        jPanel1.setLayout(null);

        jPanel1.setToolTipText("document settings");
        jPanel1.setName("");
        jLabel1.setText("Set parameters for your new document");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 430, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 90, 120, 19);

        jRadioButton1.setText("height");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(240, 80, 60, 40);

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("width");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(170, 80, 70, 40);

        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(170, 180, 140, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("golden ratio");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 190, 110, 14);

        Presets.setToolTipText("Presets");
        Presets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresetsActionPerformed(evt);
            }
        });

        jPanel1.add(Presets);
        Presets.setBounds(30, 50, 200, 22);

        jTabbedPane1.addTab("Dimensions", jPanel1);

        jPanel2.setLayout(null);

        jPanel2.setToolTipText("Grid settings");
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("rows");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 60, 60, 14);

        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(120, 50, 60, 30);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Fibonacci  series");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(220, 50, 140, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("columns");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 100, 60, 14);

        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(120, 90, 60, 22);

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Fibonacci series");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(220, 90, 120, 23);

        jTabbedPane1.addTab("Grid", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 400, 270);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton1);

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton2);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(190, 290, 180, 40);

        pack();
    }//GEN-END:initComponents

    private void PresetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresetsActionPerformed
        // Add your handling code here:
        int a = preset_x[Presets.getSelectedIndex()];
        String s = new Integer(a).toString();
        jTextField1.setText(s);
           //jTextField1.setText(new String(preset_x[Presets.getSelectedIndex()]));
    }//GEN-LAST:event_PresetsActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // Add your handling code here:
        jComboBox2.removeAllItems();
        if(jCheckBox2.isSelected()){
        //fill with fibo
            for(int a = 0; a<=8; a++){
            jComboBox2.addItem(fibo[a]);
        }
        }else{
          //fill with normal
         for(int a = 0; a<=24; a++){
            jComboBox2.addItem(new Integer(a).toString());
        }
        }
        jComboBox2.setSelectedIndex(5);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // Add your handling code here:
         jComboBox1.removeAllItems();
         if(jCheckBox1.isSelected()){
        //fill with fibo
            for(int a = 0; a<=8; a++){
            jComboBox1.addItem(fibo[a]);
        }
        }else{
          //fill with normal
         for(int a = 0; a<=24; a++){
            jComboBox1.addItem(new Integer(a).toString());
        }
        }
        jComboBox1.setSelectedIndex(5);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Add your handling code here:
        /*
        if(jRadioButton1.isSelected()){
        height = Integer.parseInt(jTextField1.getText());
        width = (int)(height*kerroindouble[jComboBox1.getSelectedIndex()]);
    }else{
         width = Integer.parseInt(jTextField1.getText());
          height = (int)(width*kerroindouble[jComboBox1.getSelectedIndex()]);
    }
         **/
    }//GEN-LAST:event_jTextField1ActionPerformed
/**
 * CANCEL button pressed, closes dialog
 **/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
/**
 * create new document
 **/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
        if(!jTextField1.getText().equals("")){
          if(jRadioButton1.isSelected()){
            height = Integer.parseInt(jTextField1.getText());
            width = (int)(height*kerroindouble[jComboBox3.getSelectedIndex()]);
        }else if(jRadioButton2.isSelected()){
            width = Integer.parseInt(jTextField1.getText());            
            height = (int)(width*kerroindouble[jComboBox3.getSelectedIndex()]);
        }
        }
      //  String filu = jTextField2.getText();
    /**
        AutomataDocument ad = new AutomataDocument(height, width);  
       */ 
        //pitää olla molemmat fibonappulat valittuja!!!!! muuten bugaa
        AutomataEngine engine = new AutomataEngine();
        AutomataDocument ad = new AutomataDocument(parent, engine.laskeKultainen(fiboint[jComboBox1.getSelectedIndex()], width), engine.laskeKultainen(fiboint[jComboBox2.getSelectedIndex()], height), height, width);    
  
        //asetettu = true;
        //    height = Integer.parseInt(heightBox.getText());
         //   width = Integer.parseInt(widthBox.getText());
        parent.addWindow(ad, height, width);
            setVisible(false);
            dispose();
            return;   
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new CreateGrid(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Presets;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
