/*
 * ToolsPalette.java
 *
 * Created on 29. joulukuuta 2003, 23:22
 */

package org.rikastamo.automata;

/**
 *
 * @author  rannala
 */
public class ToolsPalette extends javax.swing.JInternalFrame {
    
    /** Creates new form ToolsPalette */
    public ToolsPalette() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        selectButton = new javax.swing.JButton();
        textButton = new javax.swing.JButton();
        guideButton = new javax.swing.JButton();
        rectangleButton = new javax.swing.JButton();
        imageButton = new javax.swing.JButton();
        moveButton = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridLayout(3, 2));

        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(400, 40));
        setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        selectButton.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Raino\\Mina dokument\\valitse.gif"));
        selectButton.setText("select");
        selectButton.setToolTipText("select objects");
        selectButton.setMaximumSize(new java.awt.Dimension(81, 81));
        selectButton.setNextFocusableComponent(moveButton);
        selectButton.setPreferredSize(new java.awt.Dimension(50, 50));
        selectButton.setSelected(true);
        jPanel1.add(selectButton);

        textButton.setText("paint");
        textButton.setToolTipText("change object's color");
        jPanel1.add(textButton);

        guideButton.setText("guide");
        guideButton.setToolTipText("draw guide");
        jPanel1.add(guideButton);

        rectangleButton.setText("rectangle");
        rectangleButton.setToolTipText("draw rectangle");
        jPanel1.add(rectangleButton);

        imageButton.setText("image");
        imageButton.setToolTipText("add image");
        jPanel1.add(imageButton);

        moveButton.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Raino\\Mina dokument\\risti.gif"));
        moveButton.setText("move");
        moveButton.setToolTipText("move selected object");
        moveButton.setMaximumSize(new java.awt.Dimension(20, 20));
        moveButton.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(moveButton);

        getContentPane().add(jPanel1);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guideButton;
    private javax.swing.JButton imageButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton moveButton;
    private javax.swing.JButton rectangleButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JButton textButton;
    // End of variables declaration//GEN-END:variables
    
}
